#!/bin/sh
# kbdconfig - A very light-weight text-based keyboard configuration tool.
# (C) Klaus Knopper Jun 2001
# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

XDIALOG_HIGH_DIALOG_COMPAT=1
export XDIALOG_HIGH_DIALOG_COMPAT
  
TMP="$(mktemp -p /tmp/ kbdconfig-XXXXXXXXXX)"
 
bailout() {
   rm -f "$TMP"
   exit $1
}

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

trap bailout 2 15
    
rm -f "$TMP"

[ -f /etc/sysconfig/i18n ] &&     source /etc/sysconfig/i18n
[ -f /etc/sysconfig/keyboard ] && source /etc/sysconfig/keyboard

case "$LANG" in
	de*|at*|ch)
		TITLE="Bitte wählen Sie Ihr Keyboard"
		;;
	es*)
		TITLE="Por favor, seleccione el teclado"
		;;
	*)
		TITLE="Please choose keyboard"
		;;
esac

for i in `find /usr/share/keymaps -name \*kmap\*`; do
	FILE="${i%%.kmap*}"; NAME="${FILE##*/}"
	[ "$NAME" != "$KEYTABLE" ] && KEYMAPS="$KEYMAPS ${NAME%%-*} $NAME"
done

DEFAULT="${KEYTABLE%%-*} $KEYTABLE"

dialog --clear --title "$TITLE" --menu "Default: ${KEYTABLE:-none}" 22 70 15 $DEFAULT $KEYMAPS 2>"$TMP"

KEYTABLE="`cat $TMP`"
if [ -n "$KEYTABLE" ]; then
	echo "KEYTABLE=\"$KEYTABLE\"" >>/etc/sysconfig/keyboard
	echo "KEYTABLE=\"$KEYTABLE\"" >>/etc/sysconfig/knoppix
	loadkeys "$KEYTABLE"
fi

bailout 0

